name: Deploy backend

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Trigger Render deploy
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
