name: Deploy frontend

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Trigger Vercel deploy
        run: |
          cd client
          npx vercel --prod --yes --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
